app = 'geekcode-app' 
primary_region = 'nrt'

[build]
  image = 'mysql:8'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true # コンテナをずっと稼働させたい時はここをfalseにする
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb' # デプロイ時にメモリ不足になる可能性があるため、1GBに設定
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""

[mounts]
  source = "mysqldata"
  destination = "/data"
